### ISSUE TITLE
Missing badges in readme

### ISSUE THREAD

**Issue by olivif** [IonicaBizau/is-semver#1]
Something wrong with the badges in readme? 

![image](https://cloud.githubusercontent.com/assets/7736961/12702358/20cc54ce-c827-11e5-9e48-e965e6af7a72.png)

**Comment by IonicaBizau** [comment]
@olivif Yeah... shields.io is down and I'm lazy enough to modify my README.md template. :grin: Hope somebody will take care of the issue. :pray: 

/cc https://github.com/badges/shields/issues/645

**Comment by olivif** [comment]
@IonicaBizau ah got it! thought I'd mention it just in case you're not aware :smile:

**Comment by IonicaBizau** [comment]
@olivif Thanks! :smile: I don't usually read my readme files tho, because I just generate them. :joy: 

Related issues:
- https://github.com/badges/shields/issues/634
- https://github.com/badges/shields/issues/635

**Comment by olivif** [comment]
@IonicaBizau No worries! Yeah I had a quick look through their issues, seems like they changed the provider not too long ago and it's been a bit dodgy since then. Let's hope they fix it soon :smile:
